# -*- coding: utf-8 -*-
"""Oscillations Waves and Optics assignment 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IoqSwGhp69wujU5luAYEgeLy-yZqBUEY
"""

import matplotlib.pyplot as plt
import numpy as np

A= float(input("enter Amplitude here: "))
Ma= float(input("enter Mass here: "))
Mb=Ma
W1=1
W2=float(input("enter Omega 2 value here: "))
t= np.arange(0,250,0.01) #np.array(t0,tf,dt)
Xa = (A/(Ma +Mb)) *(Ma*(np.cos(W1*t)) + Mb*(np.cos(W2*t)))
plt.plot(t,Xa)
plt.xlabel("TIME (s)")
plt.ylabel("Xa (Unit Length)")
plt.title("I: W1= 1rad/s, W2=1.6 rad/s")
plt.show()

A= float(input("enter Amplitude here: "))
Ma= float(input("enter Mass here: "))
Mb=Ma
W1=1
W2=float(input("enter Omega 2 value here: "))
t= np.arange(0,250,0.01) #np.array(t0,tf,dt)
Xb = (A*Ma/(Ma +Mb)) *((np.cos(W1*t)) + (np.cos(W2*t)))
plt.plot(t,Xb)
plt.xlabel("TIME (s)")
plt.ylabel("Xb (Unit Length)")
plt.title("I: W1= 1rad/s, W2=1.6rad/s")
plt.show()

E = 1
W1=1
W2= float(input("enter value of Omega 2 here: "))
t = np.arange(0,250,0.01)

Ea= (E/2)*(np.cos((W1-W2)*t))
plt.plot(t,Ea)
plt.xlabel("TIME (s)")
plt.ylabel("Ea (Unit Energy)")
plt.title("I: W1= 1rad/s, W2=1.6rad/s")
plt.show()

E = 1
W1=1
W2= float(input("enter value of Omega 2 here: "))
t = np.arange(0,250,0.01)

Eb= (E/2)*(1- np.cos((W1-W2)*t))
plt.plot(t,Eb)
plt.xlabel("TIME (s)")
plt.ylabel("Eb (Unit Energy)")
plt.title("I: W1= 1rad/s, W2=1.6rad/s")
plt.show()